### ISSUE TITLE
Mix-up of names

### ISSUE THREAD

**Issue by geraldpainsi** [robertpainsi/promptig#1]
Using the install instructions in the README will not work since the repo clones into **promtig**, but the executable is called **promptig** (with 2 **p**s).

**Comment by robertpainsi** [comment]
Thanks for reporting! :smiley_cat:

Fixed by renaming the repo to promptig! Don't forget to update your remote URL.
`git remote set-url origin URL` where URL is either `https://github.com/robertpainsi/promptig.git` or `git@github.com:robertpainsi/promptig.git`
